name: Build and Test app

on: 
  push:
    branches: [master]
    
jobs:
  build:
    runs-on: [macos-latest]
    env:
      XC_VERSION: ${{ '11.4' }}
      XC_WORKSPACE: ${{ 'converzone.xcworkspace' }}
      #XC_SCHEME:  ${{ 'converzone' }}
      XC_SCHEME_TESTS: ${{ 'converzoneTests' }}
    steps:
    - name: Select latest Xcode
      run: "sudo xcode-select -s /Applications/Xcode_$XC_VERSION.app"
    - uses: actions/checkout@v2
    #- name: Build
      #run: /usr/bin/xcodebuild build -workspace "$XC_WORKSPACE" -scheme "$XC_SCHEME"
    - name: Run Unit Tests
      run: /usr/bin/xcodebuild test -workspace "$XC_WORKSPACE" -scheme "$XC_SCHEME_TESTS" -destination 'platform=iOS Simulator,name=iPhone 11'
